version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Denver"
    open-pull-requests-limit: 10
    reviewers:
      - "MateoClagg"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Only update if tests pass
    versioning-strategy: "increase"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"  
      day: "monday"
      time: "09:00"
      timezone: "America/Denver"
    open-pull-requests-limit: 5
    reviewers:
      - "MateoClagg"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"