name: Daily Stock Ingestion

on:
  schedule:
    - cron: '0 14 * * *' # Runs every day at 8 AM CST (14 UTC)
  workflow_dispatch:      # Allows manual triggering

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install awscli  # AWS CLI installed via pip is often more up to date

    - name: Create .env file from secret
      run: echo "POLYGON_API_KEY=${{ secrets.POLYGON_API_KEY }}" > .env

    - name: Set AWS credentials
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

    - name: Run ingestion script
      run: python stock_pipeline/ingestion/polygon_ingest.py

    - name: Upload only today's folder to S3 (CST adjusted)
      run: |
        CST_DATE=$(date -u -d '6 hours ago' +'%Y-%m-%d')
        aws s3 cp stock_pipeline/storage/raw/$CST_DATE/ s3://e2e-stock-pipeline-data/stock_pipeline/raw/$CST_DATE/ --recursive
    
